export default {
  GET_USER_TOKEN: 'GET_USER_TOKEN',
  GET_USER_TOKEN_SUCCESS: 'GET_USER_TOKEN_SUCCESS',
  GET_USER_TOKEN_ERROR: 'GET_USER_TOKEN_ERROR',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
  LOGIN_REQUEST_ERROR: 'LOGIN_REQUEST_ERROR',
};
