export default {
    /* Dates */
    HIGHLEVEL_SET_DATES: 'HIGHLEVEL_SET_DATES',
    HIGHLEVEL_RESET_DATES: 'HIGHLEVEL_RESET_DATES',
    HIGHLEVEL_CLEAR_DATES: 'HIGHLEVEL_CLEAR_DATES',
    /* Costs */
    HIGHLEVEL_COSTS_REQUEST: 'HIGHLEVEL_COSTS_REQUEST',
    HIGHLEVEL_COSTS_SUCCESS: 'HIGHLEVEL_COSTS_SUCCESS',
    HIGHLEVEL_COSTS_ERROR: 'HIGHLEVEL_COSTS_ERROR',
    /* Events */
    HIGHLEVEL_EVENTS_REQUEST: 'HIGHLEVEL_EVENTS_REQUEST',
    HIGHLEVEL_EVENTS_SUCCESS: 'HIGHLEVEL_EVENTS_SUCCESS',
    HIGHLEVEL_EVENTS_ERROR: 'HIGHLEVEL_EVENTS_ERROR',
  };
  