export default {
  AWS_GET_ACCOUNTS: 'AWS_GET_ACCOUNTS',
  AWS_GET_ACCOUNTS_SUCCESS: 'AWS_GET_ACCOUNTS_SUCCESS',
  AWS_GET_ACCOUNTS_ERROR: 'AWS_GET_ACCOUNTS_ERROR',
  AWS_NEW_ACCOUNT: 'AWS_NEW_ACCOUNT',
  AWS_NEW_ACCOUNT_SUCCESS: 'AWS_NEW_ACCOUNT_SUCCESS',
  AWS_NEW_ACCOUNT_ERROR: 'AWS_NEW_ACCOUNT_ERROR',
};
