export default {
  AWS_GET_COSTS: 'AWS_GET_COSTS',
  AWS_GET_COSTS_SUCCESS: 'AWS_GET_COSTS_SUCCESS',
  AWS_GET_COSTS_ERROR: 'AWS_GET_COSTS_ERROR',
  AWS_CLEAR_COSTS_DATES: 'AWS_CLEAR_COSTS_DATES',
  AWS_SET_COSTS_DATES: 'AWS_SET_COSTS_DATES',
  AWS_CLEAR_COSTS_INTERVAL: 'AWS_CLEAR_COSTS_INTERVAL',
  AWS_SET_COSTS_INTERVAL: 'AWS_SET_COSTS_INTERVAL',
  AWS_SET_COSTS_FILTER: 'AWS_SET_COSTS_FILTER',
  AWS_CLEAR_COSTS_FILTER: 'AWS_CLEAR_COSTS_FILTER'
};
