export default {
  /* AWS account */
  AWS_RESOURCES_ACCOUNT_SELECTION: 'AWS_RESOURCES_ACCOUNT_SELECTION',

  /* EC2 */
  AWS_RESOURCES_GET_EC2: 'AWS_RESOURCES_GET_EC2',
  AWS_RESOURCES_GET_EC2_SUCCESS: 'AWS_RESOURCES_GET_EC2_SUCCESS',
  AWS_RESOURCES_GET_EC2_ERROR: 'AWS_RESOURCES_GET_EC2_ERROR',
  AWS_RESOURCES_GET_EC2_CLEAR: 'AWS_RESOURCES_GET_EC2_CLEAR',

  /* RDS */
  AWS_RESOURCES_GET_RDS: 'AWS_RESOURCES_GET_RDS',
  AWS_RESOURCES_GET_RDS_SUCCESS: 'AWS_RESOURCES_GET_RDS_SUCCESS',
  AWS_RESOURCES_GET_RDS_ERROR: 'AWS_RESOURCES_GET_RDS_ERROR',
  AWS_RESOURCES_GET_RDS_CLEAR: 'AWS_RESOURCES_GET_RDS_CLEAR',
};
