export default {
  AWS_GET_S3_DATA: 'AWS_GET_S3_DATA',
  AWS_GET_S3_DATA_SUCCESS: 'AWS_GET_S3_DATA_SUCCESS',
  AWS_GET_S3_DATA_ERROR: 'AWS_GET_S3_DATA_ERROR',
  AWS_SET_S3_VIEW_DATES: 'AWS_SET_S3_VIEW_DATES'
};
