export default {
  /* Load tags charts from LocalStorage */
  AWS_TAGS_LOAD_CHARTS: 'AWS_TAGS_LOAD_CHARTS',
  AWS_TAGS_LOAD_CHARTS_ERROR: 'AWS_TAGS_LOAD_CHARTS_ERROR',
  AWS_TAGS_INSERT_CHARTS: 'AWS_TAGS_INSERT_CHARTS',
  AWS_TAGS_INSERT_DATES: 'AWS_TAGS_INSERT_DATES',
  AWS_TAGS_INSERT_FILTERS: 'AWS_TAGS_INSERT_FILTERS',

  /* Charts initialization */
  AWS_TAGS_INIT_CHARTS: 'AWS_TAGS_INIT_CHARTS',
  AWS_TAGS_INIT_CHARTS_ERROR: 'AWS_TAGS_INIT_CHARTS_ERROR',

  /* Clean */
  AWS_TAGS_CLEAN_CHARTS: 'AWS_TAGS_CLEAN_CHARTS',

  /* Multi charts support */
  AWS_TAGS_ADD_CHART: 'AWS_TAGS_ADD_CHART',
  AWS_TAGS_REMOVE_CHART: 'AWS_TAGS_REMOVE_CHART',

  /* Keys */
  AWS_TAGS_GET_KEYS: 'AWS_TAGS_GET_KEYS',
  AWS_TAGS_GET_KEYS_SUCCESS: 'AWS_TAGS_GET_KEYS_SUCCESS',
  AWS_TAGS_GET_KEYS_ERROR: 'AWS_TAGS_GET_KEYS_ERROR',
  AWS_TAGS_GET_KEYS_CLEAR: 'AWS_TAGS_GET_KEYS_CLEAR',
  AWS_TAGS_SELECT_KEY: 'AWS_TAGS_SELECT_KEY',

  /* Dates */
  AWS_TAGS_SET_DATES: 'AWS_TAGS_SET_DATES',
  AWS_TAGS_RESET_DATES: 'AWS_TAGS_RESET_DATES',
  AWS_TAGS_CLEAR_DATES: 'AWS_TAGS_CLEAR_DATES',

  /* Values */
  AWS_TAGS_GET_VALUES: 'AWS_TAGS_GET_VALUES',
  AWS_TAGS_GET_VALUES_SUCCESS: 'AWS_TAGS_GET_VALUES_SUCCESS',
  AWS_TAGS_GET_VALUES_ERROR: 'AWS_TAGS_GET_VALUES_ERROR',

  /* Intervals */
  AWS_TAGS_SET_FILTER: 'AWS_TAGS_SET_FILTER',
  AWS_TAGS_CLEAR_FILTERS: 'AWS_TAGS_CLEAR_FILTERS',
  AWS_TAGS_RESET_FILTERS: 'AWS_TAGS_RESET_FILTERS'
};
