// Package models contains the types for schema 'trackit'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
	"time"
)

// AwsAccountMasterReportsJob represents a row from 'trackit.aws_account_master_reports_job'.
type AwsAccountMasterReportsJob struct {
	ID                          int       `json:"id"`                          // id
	AwsAccountID                int       `json:"aws_account_id"`              // aws_account_id
	Completed                   time.Time `json:"completed"`                   // completed
	WorkerID                    string    `json:"worker_id"`                   // worker_id
	Joberror                    string    `json:"jobError"`                    // jobError
	Spreadsheeterror            string    `json:"spreadsheetError"`            // spreadsheetError
	Costdifferror               string    `json:"costDiffError"`               // costDiffError
	Ec2usagereporterror         string    `json:"ec2UsageReportError"`         // ec2UsageReportError
	Rdsusagereporterror         string    `json:"rdsUsageReportError"`         // rdsUsageReportError
	Esusagereporterror          string    `json:"esUsageReportError"`          // esUsageReportError
	Elasticacheusagereporterror string    `json:"elasticacheUsageReportError"` // elasticacheUsageReportError
	Lambdausagereporterror      string    `json:"lambdaUsageReportError"`      // lambdaUsageReportError

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the AwsAccountMasterReportsJob exists in the database.
func (aamrj *AwsAccountMasterReportsJob) Exists() bool {
	return aamrj._exists
}

// Deleted provides information if the AwsAccountMasterReportsJob has been deleted from the database.
func (aamrj *AwsAccountMasterReportsJob) Deleted() bool {
	return aamrj._deleted
}

// Insert inserts the AwsAccountMasterReportsJob to the database.
func (aamrj *AwsAccountMasterReportsJob) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if aamrj._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO trackit.aws_account_master_reports_job (` +
		`aws_account_id, completed, worker_id, jobError, spreadsheetError, costDiffError, ec2UsageReportError, rdsUsageReportError, esUsageReportError, elasticacheUsageReportError, lambdaUsageReportError` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, aamrj.AwsAccountID, aamrj.Completed, aamrj.WorkerID, aamrj.Joberror, aamrj.Spreadsheeterror, aamrj.Costdifferror, aamrj.Ec2usagereporterror, aamrj.Rdsusagereporterror, aamrj.Esusagereporterror, aamrj.Elasticacheusagereporterror, aamrj.Lambdausagereporterror)
	res, err := db.Exec(sqlstr, aamrj.AwsAccountID, aamrj.Completed, aamrj.WorkerID, aamrj.Joberror, aamrj.Spreadsheeterror, aamrj.Costdifferror, aamrj.Ec2usagereporterror, aamrj.Rdsusagereporterror, aamrj.Esusagereporterror, aamrj.Elasticacheusagereporterror, aamrj.Lambdausagereporterror)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	aamrj.ID = int(id)
	aamrj._exists = true

	return nil
}

// Update updates the AwsAccountMasterReportsJob in the database.
func (aamrj *AwsAccountMasterReportsJob) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !aamrj._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if aamrj._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE trackit.aws_account_master_reports_job SET ` +
		`aws_account_id = ?, completed = ?, worker_id = ?, jobError = ?, spreadsheetError = ?, costDiffError = ?, ec2UsageReportError = ?, rdsUsageReportError = ?, esUsageReportError = ?, elasticacheUsageReportError = ?, lambdaUsageReportError = ?` +
		` WHERE id = ?`

	// run query
	XOLog(sqlstr, aamrj.AwsAccountID, aamrj.Completed, aamrj.WorkerID, aamrj.Joberror, aamrj.Spreadsheeterror, aamrj.Costdifferror, aamrj.Ec2usagereporterror, aamrj.Rdsusagereporterror, aamrj.Esusagereporterror, aamrj.Elasticacheusagereporterror, aamrj.Lambdausagereporterror, aamrj.ID)
	_, err = db.Exec(sqlstr, aamrj.AwsAccountID, aamrj.Completed, aamrj.WorkerID, aamrj.Joberror, aamrj.Spreadsheeterror, aamrj.Costdifferror, aamrj.Ec2usagereporterror, aamrj.Rdsusagereporterror, aamrj.Esusagereporterror, aamrj.Elasticacheusagereporterror, aamrj.Lambdausagereporterror, aamrj.ID)
	return err
}

// Save saves the AwsAccountMasterReportsJob to the database.
func (aamrj *AwsAccountMasterReportsJob) Save(db XODB) error {
	if aamrj.Exists() {
		return aamrj.Update(db)
	}

	return aamrj.Insert(db)
}

// Delete deletes the AwsAccountMasterReportsJob from the database.
func (aamrj *AwsAccountMasterReportsJob) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !aamrj._exists {
		return nil
	}

	// if deleted, bail
	if aamrj._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM trackit.aws_account_master_reports_job WHERE id = ?`

	// run query
	XOLog(sqlstr, aamrj.ID)
	_, err = db.Exec(sqlstr, aamrj.ID)
	if err != nil {
		return err
	}

	// set deleted
	aamrj._deleted = true

	return nil
}

// AwsAccount returns the AwsAccount associated with the AwsAccountMasterReportsJob's AwsAccountID (aws_account_id).
//
// Generated from foreign key 'aws_account_master_reports_job_ibfk_1'.
func (aamrj *AwsAccountMasterReportsJob) AwsAccount(db XODB) (*AwsAccount, error) {
	return AwsAccountByID(db, aamrj.AwsAccountID)
}

// AwsAccountMasterReportsJobByID retrieves a row from 'trackit.aws_account_master_reports_job' as a AwsAccountMasterReportsJob.
//
// Generated from index 'aws_account_master_reports_job_id_pkey'.
func AwsAccountMasterReportsJobByID(db XODB, id int) (*AwsAccountMasterReportsJob, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, aws_account_id, completed, worker_id, jobError, spreadsheetError, costDiffError, ec2UsageReportError, rdsUsageReportError, esUsageReportError, elasticacheUsageReportError, lambdaUsageReportError ` +
		`FROM trackit.aws_account_master_reports_job ` +
		`WHERE id = ?`

	// run query
	XOLog(sqlstr, id)
	aamrj := AwsAccountMasterReportsJob{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&aamrj.ID, &aamrj.AwsAccountID, &aamrj.Completed, &aamrj.WorkerID, &aamrj.Joberror, &aamrj.Spreadsheeterror, &aamrj.Costdifferror, &aamrj.Ec2usagereporterror, &aamrj.Rdsusagereporterror, &aamrj.Esusagereporterror, &aamrj.Elasticacheusagereporterror, &aamrj.Lambdausagereporterror)
	if err != nil {
		return nil, err
	}

	return &aamrj, nil
}

// AwsAccountMasterReportsJobsByAwsAccountID retrieves a row from 'trackit.aws_account_master_reports_job' as a AwsAccountMasterReportsJob.
//
// Generated from index 'foreign_aws_account'.
func AwsAccountMasterReportsJobsByAwsAccountID(db XODB, awsAccountID int) ([]*AwsAccountMasterReportsJob, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, aws_account_id, completed, worker_id, jobError, spreadsheetError, costDiffError, ec2UsageReportError, rdsUsageReportError, esUsageReportError, elasticacheUsageReportError, lambdaUsageReportError ` +
		`FROM trackit.aws_account_master_reports_job ` +
		`WHERE aws_account_id = ?`

	// run query
	XOLog(sqlstr, awsAccountID)
	q, err := db.Query(sqlstr, awsAccountID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*AwsAccountMasterReportsJob{}
	for q.Next() {
		aamrj := AwsAccountMasterReportsJob{
			_exists: true,
		}

		// scan
		err = q.Scan(&aamrj.ID, &aamrj.AwsAccountID, &aamrj.Completed, &aamrj.WorkerID, &aamrj.Joberror, &aamrj.Spreadsheeterror, &aamrj.Costdifferror, &aamrj.Ec2usagereporterror, &aamrj.Rdsusagereporterror, &aamrj.Esusagereporterror, &aamrj.Elasticacheusagereporterror, &aamrj.Lambdausagereporterror)
		if err != nil {
			return nil, err
		}

		res = append(res, &aamrj)
	}

	return res, nil
}
