// Package models contains the types for schema 'trackit'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
	"time"
)

// AwsAccountUpdateTagsJob represents a row from 'trackit.aws_account_update_tags_job'.
type AwsAccountUpdateTagsJob struct {
	ID           int       `json:"id"`             // id
	Created      time.Time `json:"created"`        // created
	AwsAccountID int       `json:"aws_account_id"` // aws_account_id
	Completed    time.Time `json:"completed"`      // completed
	WorkerID     string    `json:"worker_id"`      // worker_id
	JobError     string    `json:"job_error"`      // job_error

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the AwsAccountUpdateTagsJob exists in the database.
func (aautj *AwsAccountUpdateTagsJob) Exists() bool {
	return aautj._exists
}

// Deleted provides information if the AwsAccountUpdateTagsJob has been deleted from the database.
func (aautj *AwsAccountUpdateTagsJob) Deleted() bool {
	return aautj._deleted
}

// Insert inserts the AwsAccountUpdateTagsJob to the database.
func (aautj *AwsAccountUpdateTagsJob) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if aautj._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO trackit.aws_account_update_tags_job (` +
		`created, aws_account_id, completed, worker_id, job_error` +
		`) VALUES (` +
		`?, ?, ?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, aautj.Created, aautj.AwsAccountID, aautj.Completed, aautj.WorkerID, aautj.JobError)
	res, err := db.Exec(sqlstr, aautj.Created, aautj.AwsAccountID, aautj.Completed, aautj.WorkerID, aautj.JobError)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	aautj.ID = int(id)
	aautj._exists = true

	return nil
}

// Update updates the AwsAccountUpdateTagsJob in the database.
func (aautj *AwsAccountUpdateTagsJob) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !aautj._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if aautj._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE trackit.aws_account_update_tags_job SET ` +
		`created = ?, aws_account_id = ?, completed = ?, worker_id = ?, job_error = ?` +
		` WHERE id = ?`

	// run query
	XOLog(sqlstr, aautj.Created, aautj.AwsAccountID, aautj.Completed, aautj.WorkerID, aautj.JobError, aautj.ID)
	_, err = db.Exec(sqlstr, aautj.Created, aautj.AwsAccountID, aautj.Completed, aautj.WorkerID, aautj.JobError, aautj.ID)
	return err
}

// Save saves the AwsAccountUpdateTagsJob to the database.
func (aautj *AwsAccountUpdateTagsJob) Save(db XODB) error {
	if aautj.Exists() {
		return aautj.Update(db)
	}

	return aautj.Insert(db)
}

// Delete deletes the AwsAccountUpdateTagsJob from the database.
func (aautj *AwsAccountUpdateTagsJob) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !aautj._exists {
		return nil
	}

	// if deleted, bail
	if aautj._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM trackit.aws_account_update_tags_job WHERE id = ?`

	// run query
	XOLog(sqlstr, aautj.ID)
	_, err = db.Exec(sqlstr, aautj.ID)
	if err != nil {
		return err
	}

	// set deleted
	aautj._deleted = true

	return nil
}

// AwsAccount returns the AwsAccount associated with the AwsAccountUpdateTagsJob's AwsAccountID (aws_account_id).
//
// Generated from foreign key 'aws_account_update_tags_job_ibfk_1'.
func (aautj *AwsAccountUpdateTagsJob) AwsAccount(db XODB) (*AwsAccount, error) {
	return AwsAccountByID(db, aautj.AwsAccountID)
}

// AwsAccountUpdateTagsJobByID retrieves a row from 'trackit.aws_account_update_tags_job' as a AwsAccountUpdateTagsJob.
//
// Generated from index 'aws_account_update_tags_job_id_pkey'.
func AwsAccountUpdateTagsJobByID(db XODB, id int) (*AwsAccountUpdateTagsJob, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, created, aws_account_id, completed, worker_id, job_error ` +
		`FROM trackit.aws_account_update_tags_job ` +
		`WHERE id = ?`

	// run query
	XOLog(sqlstr, id)
	aautj := AwsAccountUpdateTagsJob{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&aautj.ID, &aautj.Created, &aautj.AwsAccountID, &aautj.Completed, &aautj.WorkerID, &aautj.JobError)
	if err != nil {
		return nil, err
	}

	return &aautj, nil
}

// AwsAccountUpdateTagsJobsByAwsAccountID retrieves a row from 'trackit.aws_account_update_tags_job' as a AwsAccountUpdateTagsJob.
//
// Generated from index 'foreign_aws_account'.
func AwsAccountUpdateTagsJobsByAwsAccountID(db XODB, awsAccountID int) ([]*AwsAccountUpdateTagsJob, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, created, aws_account_id, completed, worker_id, job_error ` +
		`FROM trackit.aws_account_update_tags_job ` +
		`WHERE aws_account_id = ?`

	// run query
	XOLog(sqlstr, awsAccountID)
	q, err := db.Query(sqlstr, awsAccountID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*AwsAccountUpdateTagsJob{}
	for q.Next() {
		aautj := AwsAccountUpdateTagsJob{
			_exists: true,
		}

		// scan
		err = q.Scan(&aautj.ID, &aautj.Created, &aautj.AwsAccountID, &aautj.Completed, &aautj.WorkerID, &aautj.JobError)
		if err != nil {
			return nil, err
		}

		res = append(res, &aautj)
	}

	return res, nil
}
