package models

// Code generated by xo. DO NOT EDIT.

import (
	"time"
)

// AwsAccountStatus represents a row from 'trackit.aws_account_status'.
type AwsAccountStatus struct {
	AwsBillRepositoryID int       `json:"aws_bill_repository_id"` // aws_bill_repository_id
	Completed           time.Time `json:"completed"`              // completed
	Error               string    `json:"error"`                  // error
}
