package models

// Code generated by xo. DO NOT EDIT.

import (
	"time"
)

// AwsAccountMasterReportsJob represents a row from 'trackit.aws_account_master_reports_job'.
type AwsAccountMasterReportsJob struct {
	ID                          int       `json:"id"`                          // id
	AwsAccountID                int       `json:"aws_account_id"`              // aws_account_id
	Completed                   time.Time `json:"completed"`                   // completed
	WorkerID                    string    `json:"worker_id"`                   // worker_id
	JobError                    string    `json:"jobError"`                    // jobError
	SpreadsheetError            string    `json:"spreadsheetError"`            // spreadsheetError
	CostDiffError               string    `json:"costDiffError"`               // costDiffError
	Ec2usageReportError         string    `json:"ec2UsageReportError"`         // ec2UsageReportError
	RdsUsageReportError         string    `json:"rdsUsageReportError"`         // rdsUsageReportError
	EsUsageReportError          string    `json:"esUsageReportError"`          // esUsageReportError
	ElasticacheUsageReportError string    `json:"elasticacheUsageReportError"` // elasticacheUsageReportError
	LambdaUsageReportError      string    `json:"lambdaUsageReportError"`      // lambdaUsageReportError
	RiEc2reportError            string    `json:"riEc2ReportError"`            // riEc2ReportError
	RiRdsReportError            string    `json:"riRdsReportError"`            // riRdsReportError
	OdToRiEc2reportError        string    `json:"odToRiEc2ReportError"`        // odToRiEc2ReportError
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the AwsAccountMasterReportsJob exists in the database.
func (aamrj *AwsAccountMasterReportsJob) Exists() bool {
	return aamrj._exists
}

// Deleted returns true when the AwsAccountMasterReportsJob has been marked for deletion from
// the database.
func (aamrj *AwsAccountMasterReportsJob) Deleted() bool {
	return aamrj._deleted
}

// Insert inserts the AwsAccountMasterReportsJob to the database.
func (aamrj *AwsAccountMasterReportsJob) Insert(db DB) error {
	switch {
	case aamrj._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case aamrj._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO trackit.aws_account_master_reports_job (` +
		`aws_account_id, completed, worker_id, jobError, spreadsheetError, costDiffError, ec2UsageReportError, rdsUsageReportError, esUsageReportError, elasticacheUsageReportError, lambdaUsageReportError, riEc2ReportError, riRdsReportError, odToRiEc2ReportError` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?` +
		`)`
	// run
	logf(sqlstr, aamrj.AwsAccountID, aamrj.Completed, aamrj.WorkerID, aamrj.JobError, aamrj.SpreadsheetError, aamrj.CostDiffError, aamrj.Ec2usageReportError, aamrj.RdsUsageReportError, aamrj.EsUsageReportError, aamrj.ElasticacheUsageReportError, aamrj.LambdaUsageReportError, aamrj.RiEc2reportError, aamrj.RiRdsReportError, aamrj.OdToRiEc2reportError)
	res, err := db.Exec(sqlstr, aamrj.AwsAccountID, aamrj.Completed, aamrj.WorkerID, aamrj.JobError, aamrj.SpreadsheetError, aamrj.CostDiffError, aamrj.Ec2usageReportError, aamrj.RdsUsageReportError, aamrj.EsUsageReportError, aamrj.ElasticacheUsageReportError, aamrj.LambdaUsageReportError, aamrj.RiEc2reportError, aamrj.RiRdsReportError, aamrj.OdToRiEc2reportError)
	if err != nil {
		return err
	}
	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	} // set primary key
	aamrj.ID = int(id)
	// set exists
	aamrj._exists = true
	return nil
}

// Update updates a AwsAccountMasterReportsJob in the database.
func (aamrj *AwsAccountMasterReportsJob) Update(db DB) error {
	switch {
	case !aamrj._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case aamrj._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with primary key
	const sqlstr = `UPDATE trackit.aws_account_master_reports_job SET ` +
		`aws_account_id = ?, completed = ?, worker_id = ?, jobError = ?, spreadsheetError = ?, costDiffError = ?, ec2UsageReportError = ?, rdsUsageReportError = ?, esUsageReportError = ?, elasticacheUsageReportError = ?, lambdaUsageReportError = ?, riEc2ReportError = ?, riRdsReportError = ?, odToRiEc2ReportError = ? ` +
		`WHERE id = ?`
	// run
	logf(sqlstr, aamrj.AwsAccountID, aamrj.Completed, aamrj.WorkerID, aamrj.JobError, aamrj.SpreadsheetError, aamrj.CostDiffError, aamrj.Ec2usageReportError, aamrj.RdsUsageReportError, aamrj.EsUsageReportError, aamrj.ElasticacheUsageReportError, aamrj.LambdaUsageReportError, aamrj.RiEc2reportError, aamrj.RiRdsReportError, aamrj.OdToRiEc2reportError, aamrj.ID)
	if _, err := db.Exec(sqlstr, aamrj.AwsAccountID, aamrj.Completed, aamrj.WorkerID, aamrj.JobError, aamrj.SpreadsheetError, aamrj.CostDiffError, aamrj.Ec2usageReportError, aamrj.RdsUsageReportError, aamrj.EsUsageReportError, aamrj.ElasticacheUsageReportError, aamrj.LambdaUsageReportError, aamrj.RiEc2reportError, aamrj.RiRdsReportError, aamrj.OdToRiEc2reportError, aamrj.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the AwsAccountMasterReportsJob to the database.
func (aamrj *AwsAccountMasterReportsJob) Save(db DB) error {
	if aamrj.Exists() {
		return aamrj.Update(db)
	}
	return aamrj.Insert(db)
}

// Upsert performs an upsert for AwsAccountMasterReportsJob.
func (aamrj *AwsAccountMasterReportsJob) Upsert(db DB) error {
	switch {
	case aamrj._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO trackit.aws_account_master_reports_job (` +
		`id, aws_account_id, completed, worker_id, jobError, spreadsheetError, costDiffError, ec2UsageReportError, rdsUsageReportError, esUsageReportError, elasticacheUsageReportError, lambdaUsageReportError, riEc2ReportError, riRdsReportError, odToRiEc2ReportError` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?` +
		`)` +
		` ON DUPLICATE KEY UPDATE ` +
		`aws_account_id = VALUES(aws_account_id), completed = VALUES(completed), worker_id = VALUES(worker_id), jobError = VALUES(jobError), spreadsheetError = VALUES(spreadsheetError), costDiffError = VALUES(costDiffError), ec2UsageReportError = VALUES(ec2UsageReportError), rdsUsageReportError = VALUES(rdsUsageReportError), esUsageReportError = VALUES(esUsageReportError), elasticacheUsageReportError = VALUES(elasticacheUsageReportError), lambdaUsageReportError = VALUES(lambdaUsageReportError), riEc2ReportError = VALUES(riEc2ReportError), riRdsReportError = VALUES(riRdsReportError), odToRiEc2ReportError = VALUES(odToRiEc2ReportError)`
	// run
	logf(sqlstr, aamrj.ID, aamrj.AwsAccountID, aamrj.Completed, aamrj.WorkerID, aamrj.JobError, aamrj.SpreadsheetError, aamrj.CostDiffError, aamrj.Ec2usageReportError, aamrj.RdsUsageReportError, aamrj.EsUsageReportError, aamrj.ElasticacheUsageReportError, aamrj.LambdaUsageReportError, aamrj.RiEc2reportError, aamrj.RiRdsReportError, aamrj.OdToRiEc2reportError)
	if _, err := db.Exec(sqlstr, aamrj.ID, aamrj.AwsAccountID, aamrj.Completed, aamrj.WorkerID, aamrj.JobError, aamrj.SpreadsheetError, aamrj.CostDiffError, aamrj.Ec2usageReportError, aamrj.RdsUsageReportError, aamrj.EsUsageReportError, aamrj.ElasticacheUsageReportError, aamrj.LambdaUsageReportError, aamrj.RiEc2reportError, aamrj.RiRdsReportError, aamrj.OdToRiEc2reportError); err != nil {
		return err
	}
	// set exists
	aamrj._exists = true
	return nil
}

// Delete deletes the AwsAccountMasterReportsJob from the database.
func (aamrj *AwsAccountMasterReportsJob) Delete(db DB) error {
	switch {
	case !aamrj._exists: // doesn't exist
		return nil
	case aamrj._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM trackit.aws_account_master_reports_job ` +
		`WHERE id = ?`
	// run
	logf(sqlstr, aamrj.ID)
	if _, err := db.Exec(sqlstr, aamrj.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	aamrj._deleted = true
	return nil
}

// AwsAccountMasterReportsJobByID retrieves a row from 'trackit.aws_account_master_reports_job' as a AwsAccountMasterReportsJob.
//
// Generated from index 'aws_account_master_reports_job_id_pkey'.
func AwsAccountMasterReportsJobByID(db DB, id int) (*AwsAccountMasterReportsJob, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, aws_account_id, completed, worker_id, jobError, spreadsheetError, costDiffError, ec2UsageReportError, rdsUsageReportError, esUsageReportError, elasticacheUsageReportError, lambdaUsageReportError, riEc2ReportError, riRdsReportError, odToRiEc2ReportError ` +
		`FROM trackit.aws_account_master_reports_job ` +
		`WHERE id = ?`
	// run
	logf(sqlstr, id)
	aamrj := AwsAccountMasterReportsJob{
		_exists: true,
	}
	if err := db.QueryRow(sqlstr, id).Scan(&aamrj.ID, &aamrj.AwsAccountID, &aamrj.Completed, &aamrj.WorkerID, &aamrj.JobError, &aamrj.SpreadsheetError, &aamrj.CostDiffError, &aamrj.Ec2usageReportError, &aamrj.RdsUsageReportError, &aamrj.EsUsageReportError, &aamrj.ElasticacheUsageReportError, &aamrj.LambdaUsageReportError, &aamrj.RiEc2reportError, &aamrj.RiRdsReportError, &aamrj.OdToRiEc2reportError); err != nil {
		return nil, logerror(err)
	}
	return &aamrj, nil
}

// AwsAccountMasterReportsJobByAwsAccountID retrieves a row from 'trackit.aws_account_master_reports_job' as a AwsAccountMasterReportsJob.
//
// Generated from index 'foreign_aws_account'.
func AwsAccountMasterReportsJobByAwsAccountID(db DB, awsAccountID int) ([]*AwsAccountMasterReportsJob, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, aws_account_id, completed, worker_id, jobError, spreadsheetError, costDiffError, ec2UsageReportError, rdsUsageReportError, esUsageReportError, elasticacheUsageReportError, lambdaUsageReportError, riEc2ReportError, riRdsReportError, odToRiEc2ReportError ` +
		`FROM trackit.aws_account_master_reports_job ` +
		`WHERE aws_account_id = ?`
	// run
	logf(sqlstr, awsAccountID)
	rows, err := db.Query(sqlstr, awsAccountID)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// process
	var res []*AwsAccountMasterReportsJob
	for rows.Next() {
		aamrj := AwsAccountMasterReportsJob{
			_exists: true,
		}
		// scan
		if err := rows.Scan(&aamrj.ID, &aamrj.AwsAccountID, &aamrj.Completed, &aamrj.WorkerID, &aamrj.JobError, &aamrj.SpreadsheetError, &aamrj.CostDiffError, &aamrj.Ec2usageReportError, &aamrj.RdsUsageReportError, &aamrj.EsUsageReportError, &aamrj.ElasticacheUsageReportError, &aamrj.LambdaUsageReportError, &aamrj.RiEc2reportError, &aamrj.RiRdsReportError, &aamrj.OdToRiEc2reportError); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &aamrj)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}

// AwsAccount returns the AwsAccount associated with the AwsAccountMasterReportsJob's (AwsAccountID).
//
// Generated from foreign key 'aws_account_master_reports_job_ibfk_1'.
func (aamrj *AwsAccountMasterReportsJob) AwsAccount(db DB) (*AwsAccount, error) {
	return AwsAccountByID(db, aamrj.AwsAccountID)
}
