package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"time"
)

// AwsAccountSpreadsheetsReportsDueUpdate represents a row from 'trackit.aws_account_spreadsheets_reports_due_update'.
type AwsAccountSpreadsheetsReportsDueUpdate struct {
	ID                              int           `json:"id"`                                 // id
	Created                         time.Time     `json:"created"`                            // created
	UserID                          int           `json:"user_id"`                            // user_id
	Pretty                          string        `json:"pretty"`                             // pretty
	RoleArn                         string        `json:"role_arn"`                           // role_arn
	External                        string        `json:"external"`                           // external
	NextUpdate                      time.Time     `json:"next_update"`                        // next_update
	Payer                           bool          `json:"payer"`                              // payer
	NextUpdatePlugins               time.Time     `json:"next_update_plugins"`                // next_update_plugins
	AwsIdentity                     string        `json:"aws_identity"`                       // aws_identity
	ParentID                        sql.NullInt64 `json:"parent_id"`                          // parent_id
	LastSpreadsheetReportGeneration time.Time     `json:"last_spreadsheet_report_generation"` // last_spreadsheet_report_generation
	NextSpreadsheetReportGeneration time.Time     `json:"next_spreadsheet_report_generation"` // next_spreadsheet_report_generation
}
