// Package models contains the types for schema 'trackit'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
	"time"
)

// AwsAccountUpdateTaggingComplianceJob represents a row from 'trackit.aws_account_update_tagging_compliance_job'.
type AwsAccountUpdateTaggingComplianceJob struct {
	ID           int       `json:"id"`             // id
	Created      time.Time `json:"created"`        // created
	AwsAccountID int       `json:"aws_account_id"` // aws_account_id
	Completed    time.Time `json:"completed"`      // completed
	WorkerID     string    `json:"worker_id"`      // worker_id
	JobError     string    `json:"job_error"`      // job_error

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the AwsAccountUpdateTaggingComplianceJob exists in the database.
func (aautcj *AwsAccountUpdateTaggingComplianceJob) Exists() bool {
	return aautcj._exists
}

// Deleted provides information if the AwsAccountUpdateTaggingComplianceJob has been deleted from the database.
func (aautcj *AwsAccountUpdateTaggingComplianceJob) Deleted() bool {
	return aautcj._deleted
}

// Insert inserts the AwsAccountUpdateTaggingComplianceJob to the database.
func (aautcj *AwsAccountUpdateTaggingComplianceJob) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if aautcj._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO trackit.aws_account_update_tagging_compliance_job (` +
		`created, aws_account_id, completed, worker_id, job_error` +
		`) VALUES (` +
		`?, ?, ?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, aautcj.Created, aautcj.AwsAccountID, aautcj.Completed, aautcj.WorkerID, aautcj.JobError)
	res, err := db.Exec(sqlstr, aautcj.Created, aautcj.AwsAccountID, aautcj.Completed, aautcj.WorkerID, aautcj.JobError)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	aautcj.ID = int(id)
	aautcj._exists = true

	return nil
}

// Update updates the AwsAccountUpdateTaggingComplianceJob in the database.
func (aautcj *AwsAccountUpdateTaggingComplianceJob) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !aautcj._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if aautcj._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE trackit.aws_account_update_tagging_compliance_job SET ` +
		`created = ?, aws_account_id = ?, completed = ?, worker_id = ?, job_error = ?` +
		` WHERE id = ?`

	// run query
	XOLog(sqlstr, aautcj.Created, aautcj.AwsAccountID, aautcj.Completed, aautcj.WorkerID, aautcj.JobError, aautcj.ID)
	_, err = db.Exec(sqlstr, aautcj.Created, aautcj.AwsAccountID, aautcj.Completed, aautcj.WorkerID, aautcj.JobError, aautcj.ID)
	return err
}

// Save saves the AwsAccountUpdateTaggingComplianceJob to the database.
func (aautcj *AwsAccountUpdateTaggingComplianceJob) Save(db XODB) error {
	if aautcj.Exists() {
		return aautcj.Update(db)
	}

	return aautcj.Insert(db)
}

// Delete deletes the AwsAccountUpdateTaggingComplianceJob from the database.
func (aautcj *AwsAccountUpdateTaggingComplianceJob) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !aautcj._exists {
		return nil
	}

	// if deleted, bail
	if aautcj._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM trackit.aws_account_update_tagging_compliance_job WHERE id = ?`

	// run query
	XOLog(sqlstr, aautcj.ID)
	_, err = db.Exec(sqlstr, aautcj.ID)
	if err != nil {
		return err
	}

	// set deleted
	aautcj._deleted = true

	return nil
}

// AwsAccount returns the AwsAccount associated with the AwsAccountUpdateTaggingComplianceJob's AwsAccountID (aws_account_id).
//
// Generated from foreign key 'aws_account_update_tagging_compliance_job_ibfk_1'.
func (aautcj *AwsAccountUpdateTaggingComplianceJob) AwsAccount(db XODB) (*AwsAccount, error) {
	return AwsAccountByID(db, aautcj.AwsAccountID)
}

// AwsAccountUpdateTaggingComplianceJobByID retrieves a row from 'trackit.aws_account_update_tagging_compliance_job' as a AwsAccountUpdateTaggingComplianceJob.
//
// Generated from index 'aws_account_update_tagging_compliance_job_id_pkey'.
func AwsAccountUpdateTaggingComplianceJobByID(db XODB, id int) (*AwsAccountUpdateTaggingComplianceJob, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, created, aws_account_id, completed, worker_id, job_error ` +
		`FROM trackit.aws_account_update_tagging_compliance_job ` +
		`WHERE id = ?`

	// run query
	XOLog(sqlstr, id)
	aautcj := AwsAccountUpdateTaggingComplianceJob{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&aautcj.ID, &aautcj.Created, &aautcj.AwsAccountID, &aautcj.Completed, &aautcj.WorkerID, &aautcj.JobError)
	if err != nil {
		return nil, err
	}

	return &aautcj, nil
}

// AwsAccountUpdateTaggingComplianceJobsByAwsAccountID retrieves a row from 'trackit.aws_account_update_tagging_compliance_job' as a AwsAccountUpdateTaggingComplianceJob.
//
// Generated from index 'foreign_aws_account'.
func AwsAccountUpdateTaggingComplianceJobsByAwsAccountID(db XODB, awsAccountID int) ([]*AwsAccountUpdateTaggingComplianceJob, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, created, aws_account_id, completed, worker_id, job_error ` +
		`FROM trackit.aws_account_update_tagging_compliance_job ` +
		`WHERE aws_account_id = ?`

	// run query
	XOLog(sqlstr, awsAccountID)
	q, err := db.Query(sqlstr, awsAccountID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*AwsAccountUpdateTaggingComplianceJob{}
	for q.Next() {
		aautcj := AwsAccountUpdateTaggingComplianceJob{
			_exists: true,
		}

		// scan
		err = q.Scan(&aautcj.ID, &aautcj.Created, &aautcj.AwsAccountID, &aautcj.Completed, &aautcj.WorkerID, &aautcj.JobError)
		if err != nil {
			return nil, err
		}

		res = append(res, &aautcj)
	}

	return res, nil
}
