// Package models contains the types for schema 'trackit'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
	"time"
)

// AwsAccountPluginsJob represents a row from 'trackit.aws_account_plugins_job'.
type AwsAccountPluginsJob struct {
	ID           int       `json:"id"`             // id
	AwsAccountID int       `json:"aws_account_id"` // aws_account_id
	Completed    time.Time `json:"completed"`      // completed
	WorkerID     string    `json:"worker_id"`      // worker_id
	Joberror     string    `json:"jobError"`       // jobError

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the AwsAccountPluginsJob exists in the database.
func (aapj *AwsAccountPluginsJob) Exists() bool {
	return aapj._exists
}

// Deleted provides information if the AwsAccountPluginsJob has been deleted from the database.
func (aapj *AwsAccountPluginsJob) Deleted() bool {
	return aapj._deleted
}

// Insert inserts the AwsAccountPluginsJob to the database.
func (aapj *AwsAccountPluginsJob) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if aapj._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO trackit.aws_account_plugins_job (` +
		`aws_account_id, completed, worker_id, jobError` +
		`) VALUES (` +
		`?, ?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, aapj.AwsAccountID, aapj.Completed, aapj.WorkerID, aapj.Joberror)
	res, err := db.Exec(sqlstr, aapj.AwsAccountID, aapj.Completed, aapj.WorkerID, aapj.Joberror)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	aapj.ID = int(id)
	aapj._exists = true

	return nil
}

// Update updates the AwsAccountPluginsJob in the database.
func (aapj *AwsAccountPluginsJob) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !aapj._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if aapj._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE trackit.aws_account_plugins_job SET ` +
		`aws_account_id = ?, completed = ?, worker_id = ?, jobError = ?` +
		` WHERE id = ?`

	// run query
	XOLog(sqlstr, aapj.AwsAccountID, aapj.Completed, aapj.WorkerID, aapj.Joberror, aapj.ID)
	_, err = db.Exec(sqlstr, aapj.AwsAccountID, aapj.Completed, aapj.WorkerID, aapj.Joberror, aapj.ID)
	return err
}

// Save saves the AwsAccountPluginsJob to the database.
func (aapj *AwsAccountPluginsJob) Save(db XODB) error {
	if aapj.Exists() {
		return aapj.Update(db)
	}

	return aapj.Insert(db)
}

// Delete deletes the AwsAccountPluginsJob from the database.
func (aapj *AwsAccountPluginsJob) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !aapj._exists {
		return nil
	}

	// if deleted, bail
	if aapj._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM trackit.aws_account_plugins_job WHERE id = ?`

	// run query
	XOLog(sqlstr, aapj.ID)
	_, err = db.Exec(sqlstr, aapj.ID)
	if err != nil {
		return err
	}

	// set deleted
	aapj._deleted = true

	return nil
}

// AwsAccount returns the AwsAccount associated with the AwsAccountPluginsJob's AwsAccountID (aws_account_id).
//
// Generated from foreign key 'aws_account_plugins_job_ibfk_1'.
func (aapj *AwsAccountPluginsJob) AwsAccount(db XODB) (*AwsAccount, error) {
	return AwsAccountByID(db, aapj.AwsAccountID)
}

// AwsAccountPluginsJobByID retrieves a row from 'trackit.aws_account_plugins_job' as a AwsAccountPluginsJob.
//
// Generated from index 'aws_account_plugins_job_id_pkey'.
func AwsAccountPluginsJobByID(db XODB, id int) (*AwsAccountPluginsJob, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, aws_account_id, completed, worker_id, jobError ` +
		`FROM trackit.aws_account_plugins_job ` +
		`WHERE id = ?`

	// run query
	XOLog(sqlstr, id)
	aapj := AwsAccountPluginsJob{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&aapj.ID, &aapj.AwsAccountID, &aapj.Completed, &aapj.WorkerID, &aapj.Joberror)
	if err != nil {
		return nil, err
	}

	return &aapj, nil
}

// AwsAccountPluginsJobsByAwsAccountID retrieves a row from 'trackit.aws_account_plugins_job' as a AwsAccountPluginsJob.
//
// Generated from index 'foreign_aws_account'.
func AwsAccountPluginsJobsByAwsAccountID(db XODB, awsAccountID int) ([]*AwsAccountPluginsJob, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, aws_account_id, completed, worker_id, jobError ` +
		`FROM trackit.aws_account_plugins_job ` +
		`WHERE aws_account_id = ?`

	// run query
	XOLog(sqlstr, awsAccountID)
	q, err := db.Query(sqlstr, awsAccountID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*AwsAccountPluginsJob{}
	for q.Next() {
		aapj := AwsAccountPluginsJob{
			_exists: true,
		}

		// scan
		err = q.Scan(&aapj.ID, &aapj.AwsAccountID, &aapj.Completed, &aapj.WorkerID, &aapj.Joberror)
		if err != nil {
			return nil, err
		}

		res = append(res, &aapj)
	}

	return res, nil
}
