// Package models contains the types for schema 'trackit'.
package models

// Code generated by xo. DO NOT EDIT.

// AwsBillRepositoryDueUpdate represents a row from 'trackit.aws_bill_repository_due_update'.
type AwsBillRepositoryDueUpdate struct {
}
