// Package models contains the types for schema 'trackit'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"time"
)

// AwsBillRepositoryDueUpdate represents a row from 'trackit.aws_bill_repository_due_update'.
type AwsBillRepositoryDueUpdate struct {
	ID                   int       `json:"id"`                     // id
	AwsAccountID         int       `json:"aws_account_id"`         // aws_account_id
	Bucket               string    `json:"bucket"`                 // bucket
	Prefix               string    `json:"prefix"`                 // prefix
	LastImportedManifest time.Time `json:"last_imported_manifest"` // last_imported_manifest
	NextUpdate           time.Time `json:"next_update"`            // next_update
}
