// Package models contains the types for schema 'trackit'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
	"time"
)

// UserUpdateMostUsedTagsJob represents a row from 'trackit.user_update_most_used_tags_job'.
type UserUpdateMostUsedTagsJob struct {
	ID        int       `json:"id"`        // id
	Created   time.Time `json:"created"`   // created
	UserID    int       `json:"user_id"`   // user_id
	Completed time.Time `json:"completed"` // completed
	WorkerID  string    `json:"worker_id"` // worker_id
	JobError  string    `json:"job_error"` // job_error

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the UserUpdateMostUsedTagsJob exists in the database.
func (uumutj *UserUpdateMostUsedTagsJob) Exists() bool {
	return uumutj._exists
}

// Deleted provides information if the UserUpdateMostUsedTagsJob has been deleted from the database.
func (uumutj *UserUpdateMostUsedTagsJob) Deleted() bool {
	return uumutj._deleted
}

// Insert inserts the UserUpdateMostUsedTagsJob to the database.
func (uumutj *UserUpdateMostUsedTagsJob) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if uumutj._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO trackit.user_update_most_used_tags_job (` +
		`created, user_id, completed, worker_id, job_error` +
		`) VALUES (` +
		`?, ?, ?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, uumutj.Created, uumutj.UserID, uumutj.Completed, uumutj.WorkerID, uumutj.JobError)
	res, err := db.Exec(sqlstr, uumutj.Created, uumutj.UserID, uumutj.Completed, uumutj.WorkerID, uumutj.JobError)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	uumutj.ID = int(id)
	uumutj._exists = true

	return nil
}

// Update updates the UserUpdateMostUsedTagsJob in the database.
func (uumutj *UserUpdateMostUsedTagsJob) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !uumutj._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if uumutj._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE trackit.user_update_most_used_tags_job SET ` +
		`created = ?, user_id = ?, completed = ?, worker_id = ?, job_error = ?` +
		` WHERE id = ?`

	// run query
	XOLog(sqlstr, uumutj.Created, uumutj.UserID, uumutj.Completed, uumutj.WorkerID, uumutj.JobError, uumutj.ID)
	_, err = db.Exec(sqlstr, uumutj.Created, uumutj.UserID, uumutj.Completed, uumutj.WorkerID, uumutj.JobError, uumutj.ID)
	return err
}

// Save saves the UserUpdateMostUsedTagsJob to the database.
func (uumutj *UserUpdateMostUsedTagsJob) Save(db XODB) error {
	if uumutj.Exists() {
		return uumutj.Update(db)
	}

	return uumutj.Insert(db)
}

// Delete deletes the UserUpdateMostUsedTagsJob from the database.
func (uumutj *UserUpdateMostUsedTagsJob) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !uumutj._exists {
		return nil
	}

	// if deleted, bail
	if uumutj._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM trackit.user_update_most_used_tags_job WHERE id = ?`

	// run query
	XOLog(sqlstr, uumutj.ID)
	_, err = db.Exec(sqlstr, uumutj.ID)
	if err != nil {
		return err
	}

	// set deleted
	uumutj._deleted = true

	return nil
}

// User returns the User associated with the UserUpdateMostUsedTagsJob's UserID (user_id).
//
// Generated from foreign key 'user_update_most_used_tags_job_ibfk_1'.
func (uumutj *UserUpdateMostUsedTagsJob) User(db XODB) (*User, error) {
	return UserByID(db, uumutj.UserID)
}

// UserUpdateMostUsedTagsJobsByUserID retrieves a row from 'trackit.user_update_most_used_tags_job' as a UserUpdateMostUsedTagsJob.
//
// Generated from index 'foreign_user'.
func UserUpdateMostUsedTagsJobsByUserID(db XODB, userID int) ([]*UserUpdateMostUsedTagsJob, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, created, user_id, completed, worker_id, job_error ` +
		`FROM trackit.user_update_most_used_tags_job ` +
		`WHERE user_id = ?`

	// run query
	XOLog(sqlstr, userID)
	q, err := db.Query(sqlstr, userID)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*UserUpdateMostUsedTagsJob{}
	for q.Next() {
		uumutj := UserUpdateMostUsedTagsJob{
			_exists: true,
		}

		// scan
		err = q.Scan(&uumutj.ID, &uumutj.Created, &uumutj.UserID, &uumutj.Completed, &uumutj.WorkerID, &uumutj.JobError)
		if err != nil {
			return nil, err
		}

		res = append(res, &uumutj)
	}

	return res, nil
}

// UserUpdateMostUsedTagsJobByID retrieves a row from 'trackit.user_update_most_used_tags_job' as a UserUpdateMostUsedTagsJob.
//
// Generated from index 'user_update_most_used_tags_job_id_pkey'.
func UserUpdateMostUsedTagsJobByID(db XODB, id int) (*UserUpdateMostUsedTagsJob, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, created, user_id, completed, worker_id, job_error ` +
		`FROM trackit.user_update_most_used_tags_job ` +
		`WHERE id = ?`

	// run query
	XOLog(sqlstr, id)
	uumutj := UserUpdateMostUsedTagsJob{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&uumutj.ID, &uumutj.Created, &uumutj.UserID, &uumutj.Completed, &uumutj.WorkerID, &uumutj.JobError)
	if err != nil {
		return nil, err
	}

	return &uumutj, nil
}
